apiVersion: v1
kind: Service
metadata:
  name: kafka-finalized
spec:
  selector:
    app: kafka-finalized
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-finalized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-finalized
  template:
    metadata:
      labels:
        app: kafka-finalized
    spec:
      containers:
        - name: kafka-finalized
          image: cristiannores/kafka-finalized-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
