apiVersion: v1
kind: Service
metadata:
  name: massive-order-injector
spec:
  selector:
    app: massive-order-injector
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massive-order-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: massive-order-injector
  template:
    metadata:
      labels:
        app: massive-order-injector
    spec:
      containers:
        - name: massive-order-injector
          image: cristiannores/massive-order-injector:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
