apiVersion: v1
kind: Service
metadata:
  name: nats-service 
  labels:
    app: nats-service
spec:
  clusterIP: None
  ports:
    - name: nats-streaming
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: nats-streaming-cluster
      protocol: TCP
      port: 6222
      targetPort: 6222
    - name: exporter
      port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: nats
